/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customers;

import Business.Airlines;
import Business.AirlinesDir;
import Business.Customer;
import Business.Flight;
import Business.FlightDir;
import UserInterface.Flights.CreateNewFlight;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Charmy
 */
public class CustomerFiltersJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;

FlightDir flightDir;

    /**
     * Creates new form CustomerJPanel
     */
    Customer cust;
    AirlinesDir airLineDir;
    
    public CustomerFiltersJPanel(JPanel userProcessContainer, AirlinesDir airLineDir) {
        initComponents();
        this.cust = new Customer();
        this.userProcessContainer=userProcessContainer;
       flightDir=new FlightDir();
        this.airLineDir=airLineDir;
        flightDir.getFlightList().clear();
        for (Airlines col : airLineDir.getAirLineList()) {
           flightDir.getFlightList().addAll(col.getFlightDir().getFlightList()); 
           
       }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        sourceTxt = new javax.swing.JTextField();
        destinationTxt = new javax.swing.JTextField();
        viewAvailableFlightsButton = new javax.swing.JButton();
        searchInfoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setText("Enter The Details for Filter");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Time");

        jLabel3.setText("Date");

        jLabel4.setText("Source");

        jLabel5.setText("Destination");

        viewAvailableFlightsButton.setText("View Available Flights");
        viewAvailableFlightsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAvailableFlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvailableFlightsButtonActionPerformed(evt);
            }
        });

        searchInfoButton.setText("Apply Filters");
        searchInfoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInfoButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(155, 155, 155))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchInfoButton)
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewAvailableFlightsButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sourceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(timeTxt)
                                .addComponent(dateTxt)
                                .addComponent(destinationTxt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewAvailableFlightsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewAvailableFlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvailableFlightsButtonActionPerformed
       ArrayList <Flight> availbleFlights = new ArrayList<Flight>();
       availbleFlights.clear();
       
        if(cust.getTime().equalsIgnoreCase(""))
       {
           JOptionPane.showMessageDialog(null, "Please Click on search Info first to apply filters");
          
           
       }
       else{
       
       for (Flight f:flightDir.getFlightList() )
       {
        if(cust.getTime().equalsIgnoreCase(f.getTime())&&cust.getDate().equals(f.getDate())&&cust.getSource().equalsIgnoreCase(f.getSource())&&cust.getDestination().equalsIgnoreCase(f.getDestination()))
       {
           availbleFlights.add(f);
           
       }
       }
        CustomerViewFlights customerViewFlights = new CustomerViewFlights(userProcessContainer,availbleFlights,airLineDir,flightDir );
        userProcessContainer.add("CustomerViewFlights",customerViewFlights);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
       }
    }//GEN-LAST:event_viewAvailableFlightsButtonActionPerformed

    private void searchInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInfoButtonActionPerformed
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
         if(!((timeTxt.getText().isEmpty())&&(sourceTxt.getText().isEmpty())&&(destinationTxt.getText().isEmpty())&&(dateTxt.getText().isEmpty())))
         {
            cust.setTime(timeTxt.getText());
            cust.setSource(sourceTxt.getText());
            cust.setDestination(destinationTxt.getText());
            Date date = null;
            boolean flag =false;
            try {
                    date = dateFormat.parse(dateTxt.getText());
                    cust.setDate(date);
                    flag =true;
                } 
            catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Enter date in yyyy-mm-dd format");
                }
       
            if (true)
            {   
                    JOptionPane.showMessageDialog(null, "Search Information saved, click on View", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
         }
         else
         {
             JOptionPane.showMessageDialog(null,"All the fields are mandatory");
         }
    }//GEN-LAST:event_searchInfoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField destinationTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton searchInfoButton;
    private javax.swing.JTextField sourceTxt;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JButton viewAvailableFlightsButton;
    // End of variables declaration//GEN-END:variables
}
